<?php

namespace App\Filament\Resources\ComplianceCaseResource\RelationManagers;

use App\ComplianceCases\ComplianceCaseArchiveManager;
use App\Enums\ComplianceCaseStatus;
use App\Models\ComplianceCaseArchiveManifest;
use Filament\Actions\Action;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class ArchiveManifestsRelationManager extends RelationManager
{
    protected static string $relationship = 'archiveManifests';

    protected static ?string $title = 'Closure archive manifests';

    public function table(Table $table): Table
    {
        return $table->modifyQueryUsing(fn ($query) => $query->with(['generator:id,name,email', 'review.reviewer:id,name,email']))
            ->columns([
                TextColumn::make('version')->sortable(),
                TextColumn::make('generator.name')->label(__('Generated by'))->searchable(),
                TextColumn::make('archive_size')->numeric()->suffix(' bytes'),
                TextColumn::make('archive_sha256')->label(__('Archive SHA-256'))->copyable()->limit(12),
                TextColumn::make('review.decision')->label(__('Review'))->badge()->placeholder(__('Pending')),
                TextColumn::make('fingerprint')->limit(12)->copyable(),
            ])->headerActions([
                Action::make('generate')->label(__('Generate archive'))->icon('heroicon-o-archive-box-arrow-down')
                    ->visible(fn (): bool => auth()->user()?->can('Manage Compliance Cases') === true
                        && $this->getOwnerRecord()->status === ComplianceCaseStatus::Closed)
                    ->schema([Textarea::make('summary')->required()->maxLength(30000)])
                    ->action(fn (array $data) => app(ComplianceCaseArchiveManager::class)->generate(auth()->user(), $this->getOwnerRecord(), $data)),
            ])->recordActions([
                Action::make('review')->visible(fn (ComplianceCaseArchiveManifest $record): bool => $record->review === null
                    && auth()->user()?->can('Manage Compliance Cases') === true
                    && auth()->id() !== $record->generated_by)
                    ->schema([
                        Select::make('decision')->options(['approved' => __('Approved'), 'rejected' => __('Rejected')])->required(),
                        Textarea::make('summary')->required()->maxLength(30000),
                    ])->action(fn (ComplianceCaseArchiveManifest $record, array $data) => app(ComplianceCaseArchiveManager::class)->review(auth()->user(), $record, $data)),
                Action::make('download')->url(fn (ComplianceCaseArchiveManifest $record): string => route('compliance-case-archives.download', $record))
                    ->openUrlInNewTab()
                    ->visible(fn (ComplianceCaseArchiveManifest $record): bool => $record->review?->decision === 'approved'),
            ])->defaultSort('version', 'desc');
    }
}
