<?php

namespace App\Filament\Resources\ComplianceCaseResource\RelationManagers;

use App\ComplianceCases\ComplianceCaseClosureReportManager;
use App\Enums\ComplianceCaseStatus;
use App\Models\ComplianceCaseClosureReport;
use Filament\Actions\Action;
use Filament\Forms\Components\Textarea;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class ClosureReportsRelationManager extends RelationManager
{
    protected static string $relationship = 'closureReports';

    protected static ?string $title = 'Governed closure reports';

    public function table(Table $table): Table
    {
        return $table->modifyQueryUsing(fn ($query) => $query->with('generator:id,name,email'))->columns([
            TextColumn::make('version')->sortable(), TextColumn::make('generator.name')->label('Generated by')->searchable(),
            TextColumn::make('generated_at')->dateTime()->sortable(), TextColumn::make('report_size')->numeric()->suffix(' bytes'),
            TextColumn::make('report_sha256')->label('PDF SHA-256')->copyable()->limit(12), TextColumn::make('fingerprint')->copyable()->limit(12),
        ])->headerActions([
            Action::make('generate')->label('Generate closure report')->icon('heroicon-o-document-text')
                ->visible(fn (): bool => $this->getOwnerRecord()->status === ComplianceCaseStatus::Closed
                    && auth()->user()?->can('Manage Compliance Cases') === true)
                ->schema([Textarea::make('executive_summary')->required()->maxLength(30000)->columnSpanFull()])
                ->action(fn (array $data) => app(ComplianceCaseClosureReportManager::class)->generate(auth()->user(), $this->getOwnerRecord(), $data)),
        ])->recordActions([
            Action::make('inspect')->modalSubmitAction(false)->modalCancelActionLabel('Close')
                ->modalContent(fn (ComplianceCaseClosureReport $record) => view('filament.compliance-case-closure-report', [
                    'report' => $record->fresh()->load('generator:id,name,email'),
                ])),
        ])->defaultSort('version', 'desc');
    }
}
