<?php

namespace App\Filament\Resources\ComplianceCaseResource\RelationManagers;

use App\ComplianceCases\ComplianceCaseClosureReportManager;
use App\ComplianceCases\ComplianceCaseClosureReportReviewManager;
use App\Enums\ComplianceCaseClosureReportReviewDecision;
use App\Enums\ComplianceCaseStatus;
use App\Models\ComplianceCaseClosureReport;
use Filament\Actions\Action;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class ClosureReportsRelationManager extends RelationManager
{
    protected static string $relationship = 'closureReports';

    protected static ?string $title = 'Governed closure reports';

    private ?int $latestReportId = null;

    private ?int $closingActorId = null;

    private ?bool $canGenerateReport = null;

    public function table(Table $table): Table
    {
        return $table->modifyQueryUsing(fn ($query) => $query->with(['generator:id,name,email', 'review.reviewer:id,name,email']))->columns([
            TextColumn::make('version')->sortable(), TextColumn::make('generator.name')->label('Generated by')->searchable(),
            TextColumn::make('generated_at')->dateTime()->sortable(), TextColumn::make('report_size')->numeric()->suffix(' bytes'),
            TextColumn::make('report_sha256')->label('PDF SHA-256')->copyable()->limit(12),
            TextColumn::make('review.decision')->label(__('Review'))->badge()->placeholder(__('Pending')),
            TextColumn::make('fingerprint')->copyable()->limit(12),
        ])->headerActions([
            Action::make('generate')->label('Generate closure report')->icon('heroicon-o-document-text')
                ->visible(fn (): bool => $this->canGenerate())
                ->schema([Textarea::make('executive_summary')->required()->maxLength(30000)->columnSpanFull()])
                ->action(fn (array $data) => app(ComplianceCaseClosureReportManager::class)->generate(auth()->user(), $this->getOwnerRecord(), $data)),
        ])->recordActions([
            Action::make('review')->label(__('Review package'))->icon('heroicon-o-check-badge')
                ->visible(fn (ComplianceCaseClosureReport $record): bool => $this->canReview($record))
                ->schema([
                    Select::make('decision')->options(ComplianceCaseClosureReportReviewDecision::class)->required(),
                    Textarea::make('summary')->required()->maxLength(30000),
                ])->action(fn (ComplianceCaseClosureReport $record, array $data) => app(ComplianceCaseClosureReportReviewManager::class)
                ->review(auth()->user(), $record, $data)),
            Action::make('inspect')->modalSubmitAction(false)->modalCancelActionLabel('Close')
                ->modalContent(fn (ComplianceCaseClosureReport $record) => view('filament.compliance-case-closure-report', [
                    'report' => $record->fresh()->load(['generator:id,name,email', 'review.reviewer:id,name,email']),
                ])),
        ])->defaultSort('version', 'desc');
    }

    private function canReview(ComplianceCaseClosureReport $report): bool
    {
        if (! auth()->user()->can('Manage Compliance Cases') || $report->review !== null
            || $report->generated_by === auth()->id()) {
            return false;
        }
        $this->latestReportId ??= (int) $this->getOwnerRecord()->closureReports()
            ->reorder()->orderByDesc('version')->value('id');
        $this->closingActorId ??= (int) $this->getOwnerRecord()->events()->reorder()->latest('version')->value('recorded_by');

        return $report->id === $this->latestReportId && auth()->id() !== $this->closingActorId;
    }

    private function canGenerate(): bool
    {
        if ($this->getOwnerRecord()->status !== ComplianceCaseStatus::Closed
            || auth()->user()?->can('Manage Compliance Cases') !== true) {
            return false;
        }

        return $this->canGenerateReport ??= (function (): bool {
            $reports = $this->getOwnerRecord()->closureReports()->with('review')->orderBy('version')->get();

            return $reports->count() < 20
                && ($reports->isEmpty() || $reports->last()->review?->decision === ComplianceCaseClosureReportReviewDecision::Rejected);
        })();
    }
}
