<?php
declare(strict_types=1);
require dirname(__DIR__).'/vendor/autoload.php';
$app=require dirname(__DIR__).'/bootstrap/app.php';$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
if(DB::connection()->getDriverName()!=='mysql'||!extension_loaded('pcntl'))exit(77);
$database=(string)DB::connection()->getDatabaseName();if(!str_starts_with($database,'fynix_evidence_test_'))throw new RuntimeException('isolated evidence database required');
$connect=static function():PDO{$c=config('database.connections.mysql');return new PDO("mysql:host={$c['host']};port={$c['port']};dbname={$c['database']};charset=utf8mb4",$c['username'],$c['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_EMULATE_PREPARES=>false]);};
$profile='fynix-cyberaudit/deploy-release';$requestId='10000000-0000-4000-8000-000000000001';$operationId='20000000-0000-4000-8000-000000000001';$digest=str_repeat('a',64);$now=gmdate('Y-m-d H:i:s');$retention=gmdate('Y-m-d H:i:s',time()+86400);
DB::table('evidence_authorization_audit')->delete();DB::table('evidence_authorization_claims')->delete();DB::table('evidence_authorizations')->delete();
$forks=static function(int $count,callable $work,string $failure):void{$children=[];for($i=0;$i<$count;$i++){if(($pid=pcntl_fork())===0){$work($i);exit(0);}$children[]=$pid;}foreach($children as $pid){pcntl_waitpid($pid,$status);if(pcntl_wexitstatus($status)!==0)throw new RuntimeException($failure);}};
$forks(8,static function()use($connect,$profile,$requestId,$operationId,$digest,$now,$retention):void{$db=$connect();try{$q=$db->prepare('INSERT INTO evidence_authorizations(profile,company_id,suite_tenant_id,customer_id,requester_key_id,authority_binding_version,request_id,operation_id,request_digest,request_json,status,retention_until,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$q->execute([$profile,1,'00000000-0000-0000-0000-000000000001','4b982d36-4437-4f19-a51d-709a9ccfae8f','mysql-key',1,$requestId,$operationId,$digest,'{}','accepted',$retention,$now,$now]);}catch(PDOException $e){if(($e->errorInfo[1]??null)!==1062)exit(2);}},'create concurrency was not normalized');
$db=$connect();if((int)$db->query("SELECT COUNT(*) FROM evidence_authorizations WHERE request_id='$requestId'")->fetchColumn()!==1)throw new RuntimeException('idempotent create failed');$id=(int)$db->query("SELECT id FROM evidence_authorizations WHERE request_id='$requestId'")->fetchColumn();
$forks(8,static function(int $i)use($connect,$id,$now):void{$db=$connect();try{$q=$db->prepare('INSERT INTO evidence_authorization_claims(authorization_id,nonce,token_digest,issued_at,expires_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?)');$q->execute([$id,sprintf('30000000-0000-4000-8000-%012d',$i),hash('sha256',"token-$i"),$now,gmdate('Y-m-d H:i:s',time()+600),$now,$now]);}catch(PDOException $e){if(($e->errorInfo[1]??null)!==1062)exit(3);}},'claim concurrency was not normalized');
$db=$connect();if((int)$db->query("SELECT COUNT(*) FROM evidence_authorization_claims WHERE authorization_id=$id")->fetchColumn()!==1)throw new RuntimeException('one-time claim failed');$token=(string)$db->query("SELECT token_digest FROM evidence_authorization_claims WHERE authorization_id=$id")->fetchColumn();$receipt=hash('sha256',$digest);
$forks(8,static function()use($connect,$id,$token,$receipt):void{$db=$connect();for($attempt=1;$attempt<=3;$attempt++){try{$db->beginTransaction();$q=$db->prepare('SELECT token_digest,consumed_at,revoked_at FROM evidence_authorization_claims WHERE authorization_id=? FOR UPDATE');$q->execute([$id]);$claim=$q->fetch(PDO::FETCH_ASSOC);if(!$claim||!hash_equals($claim['token_digest'],$token)||$claim['revoked_at']!==null)exit(4);if($claim['consumed_at']===null){$db->prepare('UPDATE evidence_authorization_claims SET consumed_at=UTC_TIMESTAMP() WHERE authorization_id=? AND consumed_at IS NULL')->execute([$id]);$db->prepare('UPDATE evidence_authorizations SET consumed_at=UTC_TIMESTAMP(),receipt_digest=? WHERE id=? AND consumed_at IS NULL')->execute([$receipt,$id]);}else{$q=$db->prepare('SELECT receipt_digest FROM evidence_authorizations WHERE id=?');$q->execute([$id]);if(!hash_equals((string)$q->fetchColumn(),$receipt))exit(5);}$db->commit();return;}catch(PDOException $e){if($db->inTransaction())$db->rollBack();$retry=(string)$e->getCode()==='40001'||in_array($e->errorInfo[1]??null,[1205,1213],true);if(!$retry||$attempt===3)exit(6);usleep(20_000*$attempt);}}},'consume/replay deadlock or timeout escaped retry normalization');
$db=$connect();if((int)$db->query("SELECT COUNT(*) FROM evidence_authorizations WHERE id=$id AND consumed_at IS NOT NULL AND receipt_digest='$receipt'")->fetchColumn()!==1)throw new RuntimeException('idempotent consume/replay failed');echo "real application MySQL concurrency: passed\n";
