<?php

namespace App\Filament\Resources\IncidentResource\RelationManagers;

use App\Enums\IncidentPhase;
use App\Incidents\IncidentFinalReportManager;
use App\Models\IncidentFinalReport;
use Filament\Actions\Action;
use Filament\Forms\Components\Textarea;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Model;

class FinalReportsRelationManager extends RelationManager
{
    protected static string $relationship = 'finalReports';

    protected static ?string $title = 'Governed final incident reports';

    public static function canViewForRecord(Model $ownerRecord, string $pageClass): bool
    {
        return auth()->user()?->can('view', $ownerRecord) === true && auth()->user()?->can('Manage Incident Evidence') === true;
    }

    public function table(Table $table): Table
    {
        return $table->modifyQueryUsing(fn ($query) => $query->with('generator:id,name'))
            ->columns([
                TextColumn::make('version')->label('Version'), TextColumn::make('generator.name')->label('Generated by'),
                TextColumn::make('generated_at')->dateTime()->sortable(), TextColumn::make('report_size')->numeric()->suffix(' bytes'),
                TextColumn::make('report_sha256')->label('PDF SHA-256')->copyable()->limit(12), TextColumn::make('fingerprint')->copyable()->limit(12),
            ])->headerActions([
                Action::make('generate')->label('Generate final report')->icon('heroicon-o-document-text')
                    ->visible(fn (): bool => $this->getOwnerRecord()->phase === IncidentPhase::LessonsLearned
                        && auth()->user()?->can('update', $this->getOwnerRecord()) === true
                        && auth()->user()?->can('Manage Incident Evidence') === true)
                    ->schema([
                        Textarea::make('executive_summary')->required()->maxLength(30000)->columnSpanFull(),
                        Textarea::make('conclusions')->required()->maxLength(30000)->columnSpanFull(),
                    ])->action(fn (array $data) => app(IncidentFinalReportManager::class)->generate(auth()->user(), $this->getOwnerRecord(), $data)),
            ])->recordActions([
                Action::make('inspect')->label('Inspect')->icon('heroicon-o-eye')->modalSubmitAction(false)->modalCancelActionLabel('Close')
                    ->modalContent(fn (IncidentFinalReport $record) => view('filament.incident-final-report', ['record' => $record])),
            ])->defaultSort('version', 'desc');
    }
}
