<div class="space-y-4 text-sm">
    <dl class="grid grid-cols-1 gap-3 sm:grid-cols-2">
        <div><dt class="font-medium">Version / generated</dt><dd>v{{ $report->version }} · {{ $report->generated_at?->format('Y-m-d H:i:s') }}</dd></div>
        <div><dt class="font-medium">Generated by</dt><dd>{{ $report->generator?->name }}</dd></div>
        <div class="sm:col-span-2"><dt class="font-medium">Executive summary</dt><dd class="whitespace-pre-wrap">{{ data_get($report->report_snapshot, 'executive_summary') }}</dd></div>
        <div class="sm:col-span-2"><dt class="font-medium">Closure</dt><dd class="whitespace-pre-wrap">{{ data_get($report->report_snapshot, 'case.case.closure_summary') }}</dd></div>
        <div><dt class="font-medium">PDF SHA-256</dt><dd class="break-all font-mono text-xs">{{ $report->report_sha256 }}</dd></div>
        <div><dt class="font-medium">Evidence fingerprint</dt><dd class="break-all font-mono text-xs">{{ $report->fingerprint }}</dd></div>
    </dl>
    <a class="underline" href="{{ route('compliance-case-closure-reports.download', $report) }}">Download verified retained PDF</a>
</div>
