<div class="space-y-4 text-sm">
    <dl class="grid grid-cols-1 gap-3 sm:grid-cols-2">
        <div><dt class="font-medium">Version / generated</dt><dd>v{{ $record->version }} · {{ $record->generated_at?->format('Y-m-d H:i:s') }}</dd></div>
        <div><dt class="font-medium">Generated by</dt><dd>{{ $record->generator?->name }}</dd></div>
        <div class="sm:col-span-2"><dt class="font-medium">Executive summary</dt><dd class="whitespace-pre-wrap">{{ data_get($record->report_snapshot, 'executive_summary') }}</dd></div>
        <div><dt class="font-medium">PDF SHA-256</dt><dd class="break-all font-mono text-xs">{{ $record->report_sha256 }}</dd></div>
        <div><dt class="font-medium">Evidence fingerprint</dt><dd class="break-all font-mono text-xs">{{ $record->fingerprint }}</dd></div>
    </dl>
    <a class="underline" href="{{ route('incident-final-reports.download', $record) }}">Download verified retained PDF</a>
</div>
