#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"; cd "$root"
region="${AWS_REGION:-us-east-2}"; account=172670236523; execute=0
usage(){ echo "usage: $0 --authorization-id ID --operation-id UUID --nonce UUID --request-id UUID --company-id ID --suite-tenant-id UUID --customer-id UUID --api-key-file FILE --authority-keys FILE --soak-receipt FILE --cyber-request FILE --cyber-api-key-file FILE --cyber-authorization-id ID --cyber-nonce UUID --cyber-keys FILE --receipt-dir DIR --soak-evidence FILE --readiness-evidence FILE --previous-release SHA --previous-image sha256:... --previous-artifact SHA256 --bucket BUCKET --instance i-ID [--execute]" >&2; }
while (($#)); do case "$1" in --authorization-id) authorization_id=$2;shift 2;; --operation-id) operation_id=$2;shift 2;; --nonce) nonce=$2;shift 2;; --request-id) request_id=$2;shift 2;; --company-id) company_id=$2;shift 2;; --suite-tenant-id) suite_tenant_id=$2;shift 2;; --customer-id) customer_id=$2;shift 2;; --api-key-file) api_key=$2;shift 2;; --authority-keys) keys=$2;shift 2;; --soak-receipt) soak_receipt=$2;shift 2;; --cyber-request) cyber_request=$2;shift 2;; --cyber-api-key-file) cyber_api_key=$2;shift 2;; --cyber-authorization-id) cyber_authorization_id=$2;shift 2;; --cyber-nonce) cyber_nonce=$2;shift 2;; --cyber-keys) cyber_keys=$2;shift 2;; --receipt-dir) receipt_dir=$2;shift 2;; --soak-evidence) evidence=$2;shift 2;; --readiness-evidence) readiness=$2;shift 2;; --previous-release) previous_release=$2;shift 2;; --previous-image) previous_image=$2;shift 2;; --previous-artifact) previous_artifact=$2;shift 2;; --bucket) bucket=$2;shift 2;; --instance) instance=$2;shift 2;; --execute) execute=1;shift;; *) usage;exit 2;; esac; done
: "${authorization_id:?}" "${operation_id:?}" "${nonce:?}" "${request_id:?}" "${company_id:?}" "${suite_tenant_id:?}" "${customer_id:?}" "${api_key:?}" "${keys:?}" "${soak_receipt:?}" "${cyber_request:?}" "${cyber_api_key:?}" "${cyber_authorization_id:?}" "${cyber_nonce:?}" "${cyber_keys:?}" "${receipt_dir:?}" "${evidence:?}" "${readiness:?}" "${previous_release:?}" "${previous_image:?}" "${previous_artifact:?}" "${bucket:?}" "${instance:?}"; [[ "$instance" =~ ^i-[0-9a-f]+$ && "$bucket" =~ ^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$ ]]
test "$(git branch --show-current)" = main; test -z "$(git status --porcelain)"; git fetch --quiet origin main; revision="$(git rev-parse HEAD)"; test "$revision" = "$(git rev-parse origin/main)"; test "$(aws sts get-caller-identity --query Account --output text)" = "$account"
php artisan test; bash tests/deployment_scripts_test.sh; docker compose config -q
work="$(mktemp -d)"; trap 'rm -rf -- "$work"' EXIT; artifact="$(scripts/build-release-bundle.sh "$work")"; artifact_sha="$(sha256sum "$artifact"|cut -d' ' -f1)"; manifest_sha="$(basename "$artifact" .tar.gz|awk -F- '{print $NF}')"; tar -xOf "$artifact" manifest.json >"$work/manifest.json"; image_digest="$(jq -r .image_id "$work/manifest.json")"; soak_receipt_sha="$(jq -r .receipt_digest "$soak_receipt")"; soak_evidence_sha="$(sha256sum "$evidence"|cut -d' ' -f1)"; readiness_sha="$(sha256sum "$readiness"|cut -d' ' -f1)"
jq -nc --argjson c "$company_id" --arg t "$suite_tenant_id" --arg u "$customer_id" --arg q "$request_id" --arg r "$revision" --arg i "$image_digest" --arg a "$artifact_sha" --arg m "$manifest_sha" --arg pr "$previous_release" --arg pi "$previous_image" --arg pa "$previous_artifact" --arg sr "$soak_receipt_sha" --arg se "$soak_evidence_sha" --arg re "$readiness_sha" '{company_id:$c,suite_tenant_id:$t,customer_id:$u,request_id:$q,release_sha:$r,image_digest:$i,artifact_sha256:$a,manifest_sha256:$m,previous_release_sha:$pr,previous_image_digest:$pi,previous_artifact_sha256:$pa,rollback_ref:("fynix-release:"+$pr+"@"+$pi+"#sha256:"+$pa),soak_receipt_sha256:$sr,soak_evidence_sha256:$se,readiness_evidence_sha256:$re}' >"$work/binding.json"; chmod 0600 "$work/binding.json"
if [[ $execute != 1 ]]; then python3 scripts/validate-cyberaudit-deploy-authorization.py status --binding "$work/binding.json" --api-key-file "$api_key" --authorization-id "$authorization_id" >/dev/null; echo "validated dry run; no claim consumed; pass --execute only with release-manager approval"; exit 0; fi
python3 scripts/validate-cyberaudit-deploy-authorization.py consume --binding "$work/binding.json" --api-key-file "$api_key" --authorization-id "$authorization_id" --operation-id "$operation_id" --nonce "$nonce" --itsm-keys "$keys" --cyber-request "$cyber_request" --cyber-api-key-file "$cyber_api_key" --cyber-authorization-id "$cyber_authorization_id" --cyber-nonce "$cyber_nonce" --cyber-keys "$cyber_keys" >"$work/authority-receipt.json"; chmod 0600 "$work/authority-receipt.json"
python3 scripts/persist-release-receipts.py --directory "$receipt_dir" --operation-id "$operation_id" --itsm-receipt "$work/authority-receipt.json" --binding "$work/binding.json" >"$work/retained-receipt-index.json"; chmod 0600 "$work/retained-receipt-index.json"
key="cyberaudit/releases/$revision/$artifact_sha.tar.gz"; uri="s3://$bucket/$key"; checksum_b64="$(xxd -r -p <<<"$artifact_sha"|base64|tr -d '\n')"; version_id="$(aws s3api put-object --region "$region" --bucket "$bucket" --key "$key" --body "$artifact" --if-none-match '*' --checksum-algorithm SHA256 --checksum-sha256 "$checksum_b64" --metadata "sha256=$artifact_sha,revision=$revision" --query VersionId --output text)"; [[ "$version_id" != None && -n "$version_id" ]]; head="$(aws s3api head-object --region "$region" --bucket "$bucket" --key "$key" --version-id "$version_id" --output json)"; test "$(jq -r .Metadata.sha256 <<<"$head")" = "$artifact_sha"; test "$(jq -r .ChecksumSHA256 <<<"$head")" = "$checksum_b64"
payload="$(jq -nc --arg b "$bucket" --arg k "$key" --arg v "$version_id" --arg s "$artifact_sha" --arg r "$revision" '{commands:["set -eu","work=$(mktemp -d)","trap '\''rm -rf -- $work'\'' EXIT","aws s3api get-object --bucket "+($b|@sh)+" --key "+($k|@sh)+" --version-id "+($v|@sh)+" $work/release.tar.gz >/dev/null","test $(sha256sum $work/release.tar.gz|cut -d '\'' '\'' -f1) = "+($s|@sh),"mkdir $work/bundle","tar -xzf $work/release.tar.gz -C $work/bundle --no-same-owner","tar -xf $work/bundle/source.tar -C $work/bundle --no-same-owner","bash $work/bundle/source/deploy/aws-update.sh $work/bundle /opt/fynix-suite/cyberaudit "+($r|@sh)+" "+($s|@sh)]}')"; command_id="$(aws ssm send-command --region "$region" --instance-ids "$instance" --document-name AWS-RunShellScript --comment "CyberAudit $revision" --parameters "$payload" --query Command.CommandId --output text)"; aws ssm wait command-executed --region "$region" --command-id "$command_id" --instance-id "$instance"; aws ssm get-command-invocation --region "$region" --command-id "$command_id" --instance-id "$instance" >/dev/null
curl -fsS --max-time 20 https://cyberaudit.fynixhq.com/api/suite/ready | jq -e --arg r "$revision" '.status=="ok" and .release_sha==$r' >/dev/null; printf 'release=%s artifact_sha256=%s s3_version_id=%s ssm_command_id=%s\n' "$revision" "$artifact_sha" "$version_id" "$command_id"
